# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createBuckets <- function(x) {
    .Call(`_lshr_createBuckets`, x)
}

groupEdges <- function(from, to) {
    .Call(`_lshr_groupEdges`, from, to)
}

